using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("1.0.0.86")]
[assembly: AssemblyFileVersion("1.0.0.86")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTitle("AdminMigrationUtility.EventHandlers")]
[assembly: AssemblyDescription("This assembly contains the Admin Migration Utility Event Handlers")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Admin Migration Utility")]

